import Head from "next/head";

import Logo from "../components/Logo";

export default function Home() {
	return (
		<div className="min-h-screen bg-grey-100 text-on-surface-he">
			<Head>
				<title>Pretty Unipd</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="p-4">
				<h1 className="text-5xl font-bold mb-4">Pretty Unipd</h1>
				<p>
					A neat little extension that modifies the look of parts of
					Unipd.it and it's pages.
				</p>
			</main>
			<div className="absolute bottom-2 right-2 flex items-baseline">
				<span className="text-slate-500 mr-2">A project by </span>
				<Logo />
			</div>
		</div>
	);
}
