import Head from "next/head";

export default function Home() {
	return (
		<div className="w-32">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<h1 className="">Welcome to Pretty Unipd</h1>
			</main>
		</div>
	);
}
